spring:
  kafka:
    consumer:
      group-id: scheduled-order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.orderhub.sc.ScheduledOrder.dto.OrderEventRequest